---
packages:
  base:
    base:
    base-devel:
    curl:
    dialog:
    efibootmgr:
    git:
    grub:
    gvim:
    os-prober:
    linux:
    linux-headers:
    linux-firmware:
    networkmanager:
    netctl:
    xterm:
    wpa_supplicant:
    wget:
    zsh:
    zsh-completions:
    pacman-contrib:
    xclip:
    ntp:
    dosfstools:
    mtools:
    refind-efi:
    util-linux:
    sysstat:
    jsoncpp:
    rsync:
    parted:
    libinput:
    archlinux-appstream-data:
    archlinux-keyring:
    appstream-glib:
    tree:
    sudo:
    appstream:
    htop:
    acpi:
    freetype2:
    lsof:
    strace:
    mpd:
    playerctl:
    alsa-utils:
    pulseaudio:
    pulseaudio-alsa:
    pulseaudio-equalizer:
    pulseaudio-jack:
    pulseaudio-lirc:
    pulseaudio-zeroconf:
    pulseaudio-bluetooth:
    bluez:
    bluez-utils:
    blueman:
    docker:
    docker-compose:
    ruby:
    ruby-docs:
    make:
    lua:
    python:
    ctags:
    go:
    ttf-opensans:
    powerline-fonts:
    noto-fonts-emoji:
    ttf-fira-code:
    ttf-hack:
    ttf-font-awesome:
    ttf-roboto:
    ttf-ubuntu-font-family:
    notification-daemon:
    libnotify:
    geoclue:
    filelight:
    git-lfs:
    unzip:
    f2fs-tools:
    btrfs-progs:
    exfat-utils:
    ntfs-3g:
    reiserfsprogs:
    udftools:
    xfsprogs:
    nilfs-utils:
    gvfs-google:
    gvfs-goa:
    android-file-transfer:
    mtpfs:
    dhcpcd:
    android-udev:
    android-tools:
    pandoc:
    dnsutils:
      #acpilight:
    light:
    clang:
    llvm:
    acpid:
    bat:
    fd:
    fzf:
    evince:
    xdg-user-dirs:
    scrot:
    mpc:
    clipmenu:
    wireguard-tools:
    system-config-printer:
    neofetch:
    imagemagick:
    w3m:
    chafa:
    kubectl:
    ansible:
    man-db:
    man-pages:
  graphical:
    xfce4:
    xfce4-screenshooter:
    xfce4-terminal:
    sakura:
    network-manager-applet:
    nm-connection-editor:
    arandr:
    gtk2:
    gtk3:
    lightdm:
    lightdm-gtk-greeter:
    lightdm-webkit2-greeter:
    i3:
    dmenu:
    rofi:
    nitrogen:
    lxappearance:
    dunst:
    xorg-server:
    xorg-xinit:
    xorg-xrandr:
    xorg-drivers:
    xorg-apps:
    # xorg-xbacklight:
    xorg-server-xephyr:
    xorg-xmessage:
    xorg-xsetroot:
    xorg-xrdb:
    xorg-xinput:
    mousepad:
    zathura:
    gparted:
    gpart:
    feh:
    pavucontrol:
    pcmanfm-gtk3:
    vlc:
    gtk-engines:
    deluge:
    deluge-gtk:
    xscreensaver:
    telegram-desktop:
    virtualbox:
    virtualbox-host-modules-arch:
    virtualbox-guest-iso:
    libreoffice:
    viewnior:
  aur:
    - dropbox
    - altair
    - postman-bin
    - insomnia
    - polybar-git
    - google-chrome
    - breeze-amber-cursor-theme
    - pop-icon-theme-git
    - pop-gtk-theme-git
    - visual-studio-code-bin
      #spotify:
